#%RAML 1.0
title: second-example-raml
/customer:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "result":"succesfully fetching the data"
              }